### ISSUE TITLE
Learn about SNOMED ontology

### ISSUE THREAD

**Issue by joeflack4** [loinc/comp-loinc#58]
## Sub-tasks
- [ ] LOINC-SNOMED: Parts hierarchy?
  - wonder if they've also done supplemental model. If they haven't done anything there, we could leverage our OBO ecosystem here.
- [ ] #56

**Comment by matentzn** [comment]
I have written a bunch of documents about this, reach out with question / or if you want I can share the docs with you

**Comment by joeflack4** [comment]
We did read through this one google doc: [CompLOINC - “LOINC-SNOMED” alignment](https://docs.google.com/document/d/1ajEMzZ-_bvCSbO932pOb2QQ9XZ4ug_txKT5ZhJMaWC0/edit)

You can share the other docs if you think they have useful information in addition to this one.

**Comment by matentzn** [comment]
Thats good, that has the links to their confluence pages and their technical reports!

I dont think there is that much to gain here, due to the much much smaller scope of the current SNOMED - LOINC project. Good then! Let me know if I can help with anything, this is very important for some other projects I am involved in as well!
