### ISSUE TITLE
Alt output dir if `--fast-run`

### ISSUE THREAD

**Issue by joeflack4** [loinc/comp-loinc#76]
## Overview
It looks like the output dir is the same whether `--fast-run` is on or off. This can result in accidentally overwriting recent, still valid build files with these smaller ones.

**Comment by ShahimEssaid** [comment]
Yes, appending a "-fast" director suffix would be a good idea.  Also, the
fast option and its use is very hacky at this point to work around the very
slow parts. We can expand its use along with better logging to give faster
feedback. It's also limited to the creation of the entities and should
probably stay that way. It won't be useful to add this to the graph loading
since needed information will be missing with an incomplete load. But, that
part doesn't take too long anyway.
